### Задание 1

3 × (2 5 0 6 8 10 6 7 5 7) · 2 × (8 6 7 9 6 6 2 3 2 3) = (6 15 0 18 24 30 18 21 15 21) · (16 12 14 18 12 12 4 6 4 6) = (96 180 0 324 288 360 72 126 60 126) 

6 × (9 6 7 7 0 1 6 8 1 2) · 5 × (0 2 2 6 7 8 8 3 1 8) = (54 36 42 42 0 6 36 48 6 12)·(0 10 10 30 35 40 40 15 5 40) = (0 360 420 1260 0 240 1440 720 30 480)

(2 5 0 6 8 10 6 7 5 7) · (8 6 7 9 6 6 2 3 2 3) = (16 30 0 54 48 60 21 10 21)

(9 6 7 7 0 1 6 8 1 2) · (0 2 2 6 7 8 8 3 1 8) = (0 12 14 42 0 8 54 24 1 16)



In [22]:
a = np.array([2, 5, 0, 6, 8, 10, 6, 7, 5, 7])
b = np.array([8, 6, 7, 9, 6, 6, 2, 3, 2, 3])

In [23]:
(3*a)@(2*b)

1632

In [24]:
a = np.array([9, 6, 7, 7, 0, 1, 6, 8, 1, 2])
b = np.array([0, 2, 2, 6, 7, 8, 8, 3, 1, 8])

In [25]:
(6*a)@(5*b)

4950

In [26]:
a = np.array([2, 5, 0, 6, 8, 10, 6, 7, 5, 7])
b = np.array([8, 6, 7, 9, 6, 6, 2, 3, 2, 3])

In [27]:
a@b

272

In [28]:
a = np.array([9, 6, 7, 7, 0, 1, 6, 8, 1, 2])
b = np.array([0, 2, 2, 6, 7, 8, 8, 3, 1, 8])

In [29]:
a@b

165

### Задание 2

In [1]:
import numpy as np


In [2]:
list_arr_matrix1 = [[2,1,7,4],[5,6,7,3],[9,8,2,12],[11,14,15,15]]
list_arr_matrix2 = [[3,7,8,3,6],[2,5,9,4,13]]

In [3]:
def arr_transpose (list_arr):
    arr_matrix = np.array(list_arr)
    arr_transpose = arr_matrix.transpose()
    return arr_transpose

In [4]:
arr_transpose(list_arr_matrix1)

array([[ 2,  5,  9, 11],
       [ 1,  6,  8, 14],
       [ 7,  7,  2, 15],
       [ 4,  3, 12, 15]])

In [5]:
arr_transpose(list_arr_matrix2)

array([[ 3,  2],
       [ 7,  5],
       [ 8,  9],
       [ 3,  4],
       [ 6, 13]])

### Задание 3

In [7]:
from sympy import *
from sympy.plotting import plot
init_printing(use_unicode=False, wrap_line=False, no_global=True)

In [16]:
import matplotlib.pyplot as plt
import numpy as np
from sympy.abc import x as a,y as b

In [9]:
a1, a2 = symbols('a1, a2')


In [10]:
MSE = 1/4*((a1*1+a2*2-5)**2+\
           (a1*5+a2*3-6)**2+\
           (a1*2+a2*4-10)**2+\
           (a1*3+a2*7-8)**2)

In [11]:
MSE.subs({a1:0.57, a2: 0.91})

/opt/anaconda3/lib/python3.9/site-packages/IPython/lib/latextools.py:126: MatplotlibDeprecationWarning: 
The to_png function was deprecated in Matplotlib 3.4 and will be removed two minor releases later. Use mathtext.math_to_image instead.
  mt.to_png(f, s, fontsize=12, dpi=dpi, color=color)
/opt/anaconda3/lib/python3.9/site-packages/IPython/lib/latextools.py:126: MatplotlibDeprecationWarning: 
The to_rgba function was deprecated in Matplotlib 3.4 and will be removed two minor releases later. Use mathtext.math_to_image instead.
  mt.to_png(f, s, fontsize=12, dpi=dpi, color=color)
/opt/anaconda3/lib/python3.9/site-packages/IPython/lib/latextools.py:126: MatplotlibDeprecationWarning: 
The to_mask function was deprecated in Matplotlib 3.4 and will be removed two minor releases later. Use mathtext.math_to_image instead.
  mt.to_png(f, s, fontsize=12, dpi=dpi, color=color)
/opt/anaconda3/lib/python3.9/site-packages/IPython/lib/latextools.py:126: MatplotlibDeprecationWarning: 
The MathtextBa

@MSE(0.57, 0.91) = (19.5·0.57+23·0.91-39.5 23·0.57+39·0.91-62) = (11.115+20.93-39.5 13.11+35.49-62)=(-7.455 -13.4) => -@MSE = (7.455 13.4)
(0.57 0.91)+0.01·(7.455 13.4) = (0.57 0.91)+(0.07455 0.134) = (0.64455 1.044)

In [12]:
MSE.subs({a1:0.64455, a2: 1.044})

@MSE(0.64455, 1.044) = (19.5·0.64455+23·1.044-39.5 23·0.64455+39·1.044-62) = (12.568725+24.012-39.5 14.82465+40.76-62)=(-2.919275 -6.41535) => -@MSE = (2.919275 6.41535) (0.64455 1.044)+0.01·(2.919275 6.41535) = (0.64455 1.044)+(0.02919275 0.0641535) = (0.67374275 1.1081535)

In [13]:
MSE.subs({a1:0.67374275, a2:1.1081535})

@MSE(0.67374275, 1.1081535) = (19.5·0.67374275+23·1.1081535-39.5 23·0.67374275+39·1.1081535-62) = (13.1379836+25.4875305-39.5 15.4960832+43.2179865-62)=(-0.8744859 -3.2859303) => -@MSE = (0.8744859 3.2859303) (0.67374275 1.1081535)+0.01·(0.8744859 3.2859303) = (0.67374275 1.1081535)+(0.00874486 0.0328593) = (0.68248761 1.1410128)

In [15]:
MSE.subs({a1:0.68248761, a2:1.1410128})

5 шагов до спуска

In [30]:
MSE_diffa1 = diff(MSE, a1)
MSE_diffa1

In [31]:
MSE_diffa2 = diff(MSE, a2)
MSE_diffa2

In [32]:
alpha = 0.01

In [35]:
import numpy

In [36]:
numpy.array([1, 3]) - numpy.array([2, 1])

array([-1,  2])

In [40]:
point = numpy.array([0.57, 0.91])

In [42]:
gradient = numpy.array([MSE_diffa1.subs({a1: point[0], a2: point[1]}), 
                    MSE_diffa2.subs({a1: point[0], a2: point[1]})])
gradient

array([-7.45500000000000, -13.4000000000000], dtype=object)

In [45]:
next_point = point - alpha * gradient
next_point

array([0.644550000000000, 1.04400000000000], dtype=object)

In [46]:
MSE.subs({a1: next_point[0], a2: next_point[1]})

In [47]:
point = numpy.array([0.644550000000000, 1.04400000000000])

In [48]:
gradient = numpy.array([MSE_diffa1.subs({a1: point[0], a2: point[1]}), 
                    MSE_diffa2.subs({a1: point[0], a2: point[1]})])
gradient

array([-2.91927500000000, -6.45935000000000], dtype=object)

In [49]:
next_point = point - alpha * gradient
next_point

array([0.673742750000000, 1.10859350000000], dtype=object)

In [50]:
MSE.subs({a1: next_point[0], a2: next_point[1]})

In [51]:
point = numpy.array([0.673742750000000, 1.10859350000000])

In [52]:
gradient = numpy.array([MSE_diffa1.subs({a1: point[0], a2: point[1]}), 
                    MSE_diffa2.subs({a1: point[0], a2: point[1]})])
gradient

array([-0.864365875000004, -3.26877025000000], dtype=object)

In [53]:
next_point = point - alpha * gradient
next_point

array([0.682386408750000, 1.14128120250000], dtype=object)

In [54]:
MSE.subs({a1: next_point[0], a2: next_point[1]})

In [55]:
point = numpy.array([0.682386408750000, 1.14128120250000])

In [56]:
gradient = numpy.array([MSE_diffa1.subs({a1: point[0], a2: point[1]}), 
                    MSE_diffa2.subs({a1: point[0], a2: point[1]})])
gradient

array([0.0560026281250039, -1.79514570124999], dtype=object)

In [57]:
next_point = point - alpha * gradient
next_point

array([0.681826382468750, 1.15923265951250], dtype=object)

In [58]:
MSE.subs({a1: next_point[0], a2: next_point[1]})

In [59]:
point = numpy.array([0.681826382468750, 1.15923265951250])

In [60]:
gradient = numpy.array([MSE_diffa1.subs({a1: point[0], a2: point[1]}), 
                    MSE_diffa2.subs({a1: point[0], a2: point[1]})])
gradient

array([0.457965626928125, -1.10791948223125], dtype=object)

In [61]:
next_point = point - alpha * gradient
next_point

array([0.677246726199469, 1.17031185433481], dtype=object)

In [62]:
MSE.subs({a1: next_point[0], a2: next_point[1]})